apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: erp
resources:
  - namespace.yaml
  - api-gateway.yaml
  - analytics-service.yaml
  - pm-service.yaml
  - plm-service.yaml
  - finance-service.yaml
  - quality-service.yaml
  - eam-service.yaml
  - proc-service.yaml
commonLabels:
  app.kubernetes.io/managed-by: erp-kustomize
  app.kubernetes.io/version: "2026"
