apiVersion: 1

contactPoints:
  - orgId: 1
    name: erp-alertmanager
    receivers:
      - uid: erp-am-slo
        type: prometheus-alertmanager
        settings:
          url: http://alertmanager:9093
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: erp-alertmanager
    group_by: ['domain', 'severity']
    routes:
      - receiver: erp-alertmanager
        object_matchers:
          - ['domain', '=', 'slo']
