global:
  namespace: erp
  imagePullPolicy: IfNotPresent

apiGateway:
  enabled: true
  replicaCount: 2
  image: erp/api-gateway:latest
  port: 4005
  authEnforce: true

analyticsService:
  enabled: true
  replicaCount: 1
  image: erp/analytics-service:latest
  port: 4011

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
